# Generated by Django 2.1 on 2018-08-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='No title')),
                ('description', models.TextField(default='no description')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ad',
                'verbose_name_plural': 'ad_pl',
                'db_table': 'ad',
                'required_db_vendor': 'mysql',
            },
        ),
    ]
