# Generated by Django 2.1 on 2018-09-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_ad_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category_pl',
                'db_table': 'category',
                'required_db_vendor': 'mysql',
            },
        ),
    ]
