# Generated by Django 2.1 on 2018-09-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_auto_20180910_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['-creation_date'], 'verbose_name': 'ad', 'verbose_name_plural': 'ad_pl'},
        ),
    ]
