# Generated by Django 2.1 on 2018-09-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0008_favourites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'ad', 'verbose_name_plural': 'ad_pl'},
        ),
    ]
