# Generated by Django 2.1 on 2018-09-24 07:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0009_auto_20180919_1536'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ad',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
