# Generated by Django 2.1 on 2018-09-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_auto_20180924_0745'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ad',
            managers=[
            ],
        ),
    ]
