# Generated by Django 2.1 on 2018-09-24 08:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0012_auto_20180924_0755'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ad',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
