# Generated by Django 2.1 on 2018-09-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0013_auto_20180924_0812'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ad',
            managers=[
            ],
        ),
    ]
