# Generated by Django 2.1 on 2018-08-29 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalUserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('birthday', models.DateField(blank=True)),
                ('avatar', models.ImageField(upload_to='users/avatars/')),
                ('country', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('street', models.TextField(blank=True)),
                ('house_number', models.TextField(blank=True, help_text='Номер дома')),
                ('house_block', models.TextField(blank=True, help_text='Корпус дома')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_info',
                'verbose_name_plural': 'user_info_pl',
                'db_table': 'user_info',
                'required_db_vendor': 'mysql',
            },
        ),
    ]
