# Generated by Django 2.1 on 2018-08-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
