# Generated by Django 2.1 on 2018-09-05 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20180830_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(default='Ups, error')),
                ('read_status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('who_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'messages',
                'verbose_name_plural': 'messages_pl',
                'db_table': 'messages',
                'required_db_vendor': 'mysql',
            },
        ),
    ]
